### ISSUE TITLE
Intel Optane Support (Working Example)

### ISSUE THREAD

**Issue by ChrisKader** [dortania/vanilla-laptop-guide#2]
On your [macOS Limitations](https://github.com/hackintosh-guides/vanilla-laptop-guide/blob/master/overview/macos-limits.md) page, you mention that intel optane drives need to be removed or macOS wont boot.

I bought an [HP 15-dk0056nr](https://www.target.com/p/hp-15-6-34-pavilion-gaming-laptop-intel-core-i5-9300h-nvidia-geforce-gtx-1650-8gb-ram-512-gb-ssd-windows-10-15-dk0056nr/-/A-77062331) (gaming laptop).

It comes with an [Intel Optane H10](https://www.intel.com/content/www/us/en/products/memory-storage/optane-memory/optane-memory-h10-solid-state-storage.html) drive installed (on an Intel RST Raid Controller) along with another available M.2 port and a full size SATA bay for another drive. (I installed a 256GB Samsung EVO SSD). The only hardware change I made to this machine was install a compatible wireless card (No whitelist enabled so you are free to pick just about any card that works with OS X).

I have the latest version of macOS Catalina installed on it (Ironically, newer than the Catalina version installed on my official mid-2014 13" MBP). Catalina is installed on the Samsung SSD with Windows 10 on the Intel Optane drive. I am able to access the Optane drive from within Catalina and boot between both OSes with only one issue (the nVida card does not work in Catalina, but I do not look at that as an issue as there is currently no drivers available for it): I cannot get it to work with OpenCore.

When I initially setup Catalina, I only knew of OpenCore and spent about a week or so getting everything working. When I learned about OpenCore I was determined to get it working and redid the whole build and translated as much of my Clover config.plist over into OpenCore while dropping anything unnecessary. I was hoping I would be able to get your assistance with resolving this as I am fairly confident OpenCore could boot this (with the same functionality) if Clover can.

I can either clone this repo or setup my own with everything I am currently using with Clover and OpenCore and start from there.

I appreciate your time!

**Comment by dhinakg** [comment]
Interesting, will have to look into this more. We do not provide support in the issue tracker, for that you'll have to go to the subreddit or to the Discord.

**Comment by khronokernel** [comment]
I added a note a bit back, seems Catalina *mostly* fixed support but just to be on the safe side I'd still like users to be aware: https://github.com/dortania/vanilla-laptop-guide/commit/c06c87128ae0a34ed82f39db10fc3d50d56417b7
