### ISSUE TITLE
Stuck at gIOScreenLockState 3

### ISSUE THREAD

**Issue by aalpgiray** [dortania/vanilla-laptop-guide#22]
Hi,

I need direction and help. Maybe this is not a very good place to post this. But I assume you need these details to direct me to where. I am using dell latitude 5501 i7 9850h. I don't have DVMT pre-allocated setting on bios. I have used Open Core 0.5.8 and Catalina 10.5.4. I think I am stuck at this moment. 

I think it is related to GPU. I have disabled external GPU with -wegnoegpu and then tried this this 
[SSDT-dGPU-Off.dsl](https://github.com/dortania/vanilla-laptop-guide/files/4606188/SSDT-dGPU-Off.txt)

![gioscreenlocakstate](https://user-images.githubusercontent.com/6337113/81505532-8b9ba700-92f8-11ea-9a45-bcfce4e42d8b.jpg)

[config.plist](https://github.com/dortania/vanilla-laptop-guide/files/4606181/config.txt)

**Comment by khronokernel** [comment]
Little confused why you're using `<0000003e>` for platform-id and `<003e0000>` for device ID. The defaults for your CPU are actually supported, and the ones we recommend are the highlighted one([btw your iGPU needs not device-id entry](https://ark.intel.com/content/www/us/en/ark/products/191047/intel-core-i7-9850h-processor-12m-cache-up-to-4-60-ghz.html)):

| iGPU | device-id | AAPL,ig-platform-id | Port Count | Stolen Memory | Framebuffer Memory | Connectors |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **Intel UHD Graphics 630** | 9B3E0000 | 00009B3E | 3 | 57MB | 0MB |  LVDSx1 DPx2 |

While this is not a help forum, this does bring to light how our current theme makes it a bit difficult to distinguish between highlighted and regular entires so I appreciate that.  The new theme coming shows it a bit better but not all too well still so will need to find better ways to indicate recommended entires.

And again not a help forum, so closing this issue
