### ISSUE TITLE
[REQUEST] Dual battery implementation as one

### ISSUE THREAD

**Issue by Juan-VC** [dortania/vanilla-laptop-guide#37]
I recently found my laptop has two batteries and macos is only using one that is about 2/3 lf the total capacity. There is already a ssdt from rehabman for acpibattery.kext, I tried it and no luck it could be because of my acpi tables. I would like to request help implementing both batteries as one for virtualsmc and also add info about this in the guide. Thanks!

**Comment by khronokernel** [comment]
Moved this issue to the new bugtracker: https://github.com/dortania/bugtracker/issues/8
