### ISSUE TITLE
SSDT-EC Mistake

### ISSUE THREAD

**Issue by martinlhzy** [dortania/vanilla-laptop-guide#42]
There is a small erratum in the guide, which can cause a little misunderstanding.

"https://dortania.github.io/Getting-Started-With-ACPI/ssdt-platform.html"
 - The Laptop/Broadwell section says you need the SSDT-EC-USBX.dsl, while the

"https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-methods/manual.html"
- "Edits to the sample SSDT" section claims you will need the SSDT-EC.dsl.

**Comment by khronokernel** [comment]
Thank you, finally got around to fixing it: https://github.com/dortania/Getting-Started-With-ACPI/commit/17d8411fd696140b00ef132dad6adae640d51605
