### ISSUE TITLE
Intel UHD620 framebuffer (Kabylake Refresh)

### ISSUE THREAD

**Issue by rottenpants466** [dortania/vanilla-laptop-guide#5]
I was checking the intel framebuffer guide from whatevergreen and in the case of UHD620 (kabylake refresh) they recommend the following value: **device id: 16590000** and probably as well **AAPL,ig-platform-id: 00001659**

![Screenshot_20200414-192703](https://user-images.githubusercontent.com/62076029/79260563-65fcb880-7e86-11ea-9821-7b6715044a66.jpg)

In the kabylake config plist here (for UHD620) its recommended the use of: **device id: 87C00000** and **AAPL,ig-platform-id: 0000C087**

![Screenshot_20200414-193218](https://user-images.githubusercontent.com/62076029/79261168-59c52b00-7e87-11ea-9f4a-89f4986efe16.jpg)

I tried both but only the first values worked for me. Dont know if we need to change those values in that part of the guide to the whatevergreen ones.

Cheers

**Comment by midi1996** [comment]
Both values work fine (again depending on the hardware). When UHD620 (KBL-R) was released, people faked it for an HD620 which worked just fine, with the release of MBA(2018), they added these new entries for KBL-Y (found in that MBA). I mean either way works, but I've seen people having better results with the newer IDs. You can always test and check the differences!

**Comment by fewtarius** [comment]
0x5916 (00001659) is the UHD 620 found on the 7th generation Kaby Lake CPU, for example, the i7-7500U.  Another recommended value is 0x591b (00001b59) which is the UHD 630 found on the i7-7820HQ.  It is not generally the one we recommend for the 8th generation Kaby Lake Refresh though.  We've often found for the 8th gen KBL-R series we have the best luck with 0x87C0 (0000C087) which is the UHD 617 found on the i5-8210Y.

There are a lot of variables involved here, so as @midi1996 said you should test multiple properties and validate which works best on your particular system.

**Comment by rottenpants466** [comment]
Thanks for the clarification :) for me at least if i use 0000C087 i get the dreaded 7MB gpu memory

**Comment by midi1996** [comment]
What CPU do you have? Maybe it could hint us on why it doesnt work for you.

**Comment by rottenpants466** [comment]
This is a my girlfriend's laptop actually :) it still has clover on it since im unable to transition to opencore.

Its an i7 8550u with 16gb of ram and a geforce card (disabled)

**Comment by rottenpants466** [comment]
Sorry for posting again but after a few changes in the config.plist I finally got the laptop to boot with opencore :) trackpad and keyboard are not working but with time I will they will

Regarding again the framebuffer I tried using 87C00000 this time with opencore but I get 7mb of memory and lack of gpu acceleration so in my case I really need to use 16590000

I will leave here the refi

[EFI.zip](https://github.com/dortania/vanilla-laptop-guide/files/4490087/EFI.zip)

But anyway im very happy that I finally got rid of clover :) thank you for everything including these awesome guides

**Comment by codeforcesmeme** [comment]
I've almost the same hardware as the mentioned specs yet, I cannot boot the **installation usb** neither with clover nor oc with my laptop I tried your EFIs you posted but still not getting past this "error?" I have no idea what is it or why is it doing that.
what it shows with oc

![OC](https://user-images.githubusercontent.com/45147859/79566382-bfe1c600-80b2-11ea-9a94-7a499da5889c.jpg)

With clover 

![Clover](https://user-images.githubusercontent.com/45147859/79566396-c4a67a00-80b2-11ea-8dd9-2092f798f21c.jpg)

My laptop is also HP, Probook 450 g5
CPU: i7 8550u
GPU: UHD620 with Nvidia 930MX (disabled in bios)
RAM: 8gb ram DDR4

Am I missing something obvious? I know missing kexts is something common with noobs but I've been struggling for a few days now.

**Comment by midi1996** [comment]
This is not a support channel. please refer to the proper channels and also "using multiple efis" is a really bad solution.

**Comment by Sniki** [comment]
> Thanks for the clarification :) for me at least if i use 0000C087 i get the dreaded 7MB gpu memory

as seen on that picture # 2 of Post # 1 the problem is that the device-id is wrong and don't know where did people get that device-id from.

I had a [Lenovo V330-15IKB](https://github.com/Sniki/Lenovo-V330-15IKB) (Kaby Lake Refresh), we first used 5916/591B because there was no KabyLake-R Macbook, as soon as newer MacBooks released, i switched to 0000C087 because it is UHD 617 instead of just HD 620 or HD630 which are 1 generation older and don't have the U for UHD (4K) i assume that's on what they based the name on.

So UHD 617 is closer to UHD 620 which is what every KabyLake R generation laptop should use.
The problem is that the device-id should remain: 16590000

So correct Kaby Lake Refresh standard should be:
**AAPL,ig-platform-id: 0000C087
device id: 16590000**

**Comment by rottenpants466** [comment]
> > Thanks for the clarification :) for me at least if i use 0000C087 i get the dreaded 7MB gpu memory
> 
> as seen on that picture # 2 of Post # 1 the problem is that the device-id is wrong and don't know where did people get that device-id from.
> 
> I had a [Lenovo V330-15IKB](https://github.com/Sniki/Lenovo-V330-15IKB) (Kaby Lake Refresh), we first used 5916/591B because there was no KabyLake-R Macbook, as soon as newer MacBooks released, i switched to 0000C087 because it is UHD 617 instead of just HD 620 or HD630 which are 1 generation older and don't have the U for UHD (4K) i assume that's on what they based the name on.
> 
> So UHD 617 is closer to UHD 620 which is what every KabyLake R generation laptop should use.
> The problem is that the device-id should remain: 16590000
> 
> So correct Kaby Lake Refresh standard should be:
> **AAPL,ig-platform-id: 0000C087 device id: 16590000**

I don't think I tried that combination. Will test it out

**Comment by rottenpants466** [comment]
It worked, I have gpu acceleration and HDMI works ok.

**Comment by Sniki** [comment]
> It worked, I have gpu acceleration and HDMI works ok.

Great to hear that your problem is solved.
